config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  scope module: :web do
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get 'auth/logout', to: 'auth#logout'
    post 'auth/:provider', to: 'auth#request', as: :auth_request

    resources :repositories, only: %i[index show new create] do
      resources :checks, only: %w[show create], module: 'repositories'
    end
  end

  namespace :api do
    resources :checks, only: %w[create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize

  belongs_to :user
  has_many :checks, dependent: :destroy

  enumerize :language, in: %i[javascript ruby]

  validates :github_id, presence: true
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  aasm whiny_transitions: false do
    state :starting, initial: true
    state :checking
    state :finished
    state :failed

    event :start do
      transitions from: :starting, to: :checking
    end

    event :finish do
      transitions from: :checking, to: :finished
    end

    event :fail do
      transitions from: :checking, to: :failed
    end
  end

  belongs_to :repository
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :repositories, dependent: :destroy
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ApplicationController
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

class Api::ChecksController < Web::Repositories::ApplicationController
  def create; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include AuthConcern
end

app/controllers/concerns/auth_concern.rb
# frozen_string_literal: true

module AuthConcern
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    session.clear
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

class Web::AuthController < Web::ApplicationController
  def callback
    email = auth[:info][:email].downcase
    existing_user = User.find_by(email: email)

    if existing_user
      sign_in existing_user
      redirect_to root_path, notice: t('.success')
      return
    end

    user_params = {
      email: auth[:info][:email].downcase,
      image_url: auth[:info][:image],
      name: auth[:info][:name],
      nickname: auth[:info][:nickname],
      token: auth[:credentials][:token]
    }
    user = User.new(user_params)

    if user.save
      sign_in user
      redirect_to root_path, notice: t('.success')
    else
      redirect_to root_path, alert: t('.failure')
    end
  end

  def logout
    sign_out
    redirect_to root_path, notice: t('.success')
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

class Web::Repositories::ApplicationController < Web::ApplicationController
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::Repositories::ApplicationController
  def create
    check = Repository::Check.new(permitted_params)

    if check.save
      CheckRepositoryJob.perform_later check.id
      redirect_to repository_path(check.repository_id), notice: t('.success')
    else
      redirect_to repository_path(check.repository_id), alert: t('.failure')
    end
  end

  def show
    @check = Repository::Check.find(params[:id])
  end

  def permitted_params
    params.permit(:repository_id)
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < ApplicationController
  def index
    @repositories = Repository.where(user_id: current_user.id)
  end

  def show
    @repository = Repository.find(params[:id])
    @checks = @repository.checks.all.order(created_at: :desc)
  end

  def new
    @repository = Repository.new

    @repo_names = []
    client = Octokit::Client.new access_token: current_user.token, per_page: 100
    repos = client.repos
    repos.each do |repo|
      @repo_names << [repo[:full_name], repo[:id]] if Repository.language.values.include?(repo[:language]&.downcase)
    end
  end

  def create
    repository = current_user.repositories.build permitted_params

    if repository.save
      UpdateInfoRepositoryJob.perform_later repository.id, current_user.token
      redirect_to repositories_path, notice: t('.success')
    else
      render :new, alert: t('.failure')
    end
  end

  private

  def permitted_params
    params.require(:repository).permit(:github_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include AuthConcern
end

app/helpers/web/repository_helper.rb
# frozen_string_literal: true

module Web::RepositoryHelper
end

app/views/home/index.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  .display-4.fw-bold.mb-0 = t('.text1')
  p class='mb-4' = t('.text2')
  h2 class='fw-bold' = t('.text3')
  p == t('.text4')
  p
    a class='btn btn-primary btn-lg px-4 mt-3 fw-bold' href='https://ru.hexlet.io/programs/rails/projects/66' = t('.learn_more')

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title = t('.title')
    = csrf_meta_tags
    = csp_meta_tag
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body.d-flex.flex-column.h-100
    = render 'layouts/shared/nav'
    = render 'layouts/shared/flash'
    main
      .mt-4.mb-5.pb-5
        .container
          = yield
    = render 'layouts/shared/footer'

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  - flash.each do |type, msg|
    - alert_name = (type == 'alert' ? 'alert-danger' : 'alert-info')
    .container.alert.alert-dismissible.fade.show class=alert_name role='alert'
      = msg
      button.btn-close type='button' aria-label='Close' data-bs-dismiss='alert'

app/views/layouts/shared/_footer.html.slim
footer.bg-dark.text-light.mt-auto
  .container-xl
    .row.py-2 = "#{t('.hexlet')}, #{Time.zone.now.year}"

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4'
        = image_tag('logo.png', width: '30', alt: t('.alt_logo'))
      .collapse.navbar-collapse id='navbarToggler'
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          - if current_user.nil?
            li.nav-item.me-2
              = link_to t('.home'), root_path, class: 'nav-link text-dark'
          - else
            li.nav-item.me-2
              = link_to t('.home'), root_path, class: 'nav-link text-dark'
            li.nav-item.me-2
              = link_to t('.repositories'), repositories_path, class: 'nav-link text-dark'
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item
          = link_to current_user.email, '#', class: 'nav-link text-secondary'
        li.nav-item
          = link_to t('.logout'), auth_logout_path, class: 'nav-link link-dark'
      - else
        li.nav-item
          = link_to t('.sign_in'), auth_request_path(:github), method: 'post', class: 'nav-link link-dark'

app/views/web/repositories/_form.html.slim
= simple_form_for repository, url: url do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :github_id, as: :select, collection: repo_names
  = f.button :submit, class: 'btn btn-primary'

app/views/web/repositories/checks/show.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  .mb-4
    h1
  = link_to t('.go_to_repository'), repository_path(1), class: 'btn btn-primary mb-4'
  h1 Check #257
  table.table
    tr
      td = t('.created_at')
      td = @check.created_at.strftime('%B %d, %Y %H:%M')
    tr
      td = t('.status')
      td = @check.aasm.human_state
    tr
      td = t('.check_passed')
      td = @check.passed
    tr
      td = t('.issues_count')
      td = @check.issues_count
  table.table.table-hover.mb-5
    thead
      th = t('.message')
      th = t('.rule')
      th = t('.line_column')
    tbody
      - result = JSON.parse(@check.result)
      - result.each do |line, _value|
        - if line['file_path']
          tr
            td colspan='3'
              a href='https://github.com/' = line['file_path']
        - if line['message']
          tr
            td = line['message']
            td = line['rule']
            td = line['line_column']

app/views/web/repositories/index.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  .mb-4
    h1 = t('.repositories')
  = link_to t('.new'), new_repository_path, class: 'btn btn-primary'
  table.table.table-striped.table-hover.mt-4
    thead
      tr
        th = t('.name')
        th = t('.language')
        th = t('.last_check_passed')
    tbody
      - @repositories.each do |repository|
        tr
          td = link_to (repository.name.nil? ? '-' : repository.name), repository_path(repository), class: 'me-2'
          td = repository&.language
          td

app/views/web/repositories/new.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  == render 'form', repository: @repository, repo_names: @repo_names, url: repositories_path

app/views/web/repositories/show.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  .mb-4
    h1 = @repository.full_name
  = link_to t('.check'), repository_checks_path(@repository), method: :post, class: 'btn btn-primary mb-4'
  p
    strong.me-2 = "#{t('.name')}:"
    = @repository.full_name
  p
    strong.me-2 = "#{t('.language')}:"
    = @repository.language
  p
    strong.me-2 = "#{t('.created_at')}:"
    = @repository.created_at.strftime('%B %d, %Y %H:%M')
  p
    strong.me-2 = "#{t('.updated_at')}:"
    = @repository.updated_at.strftime('%B %d, %Y %H:%M')
  p
    = @repository.clone_url
  hr
  table.table.table-striped
    thead
      tr
        th
        th = t('.state')
        th = t('.reference')
        th = t('.passed')
        th = t('.created_at')
    tbody
      - @checks.each do |check|
        tr
          td = link_to check.id, repository_check_path(@repository, check)
          td = check.aasm.human_state
          td = check.reference
          td = check.passed
          td = check.created_at